Dana tablica ocen (5 studentów x 4 egzaminy):<br>
exams = np.array([
[78, 85, 92, 88],
[65, 72, 68, 70],
[90, 88, 95, 92],
[55, 60, 58, 62],
[82, 79, 85, 80]
])<br>
Dodaj bonus do każdego egzaminu: [5, 10, 5, 10]
Następnie pomnóż wyniki każdego studenta przez mnożnik: [1.0, 1.1, 0.95, 1.15, 1.0]
Wymagania:<br>
 - Użyj broadcastingu (bez pętli)
- Wypisz wyniki przed i po



In [1]:
import numpy as np

In [2]:
exams = np.array([
    [78, 85, 92, 88],
    [65, 72, 68, 70],
    [90, 88, 95, 92],
    [55, 60, 58, 62],
    [82, 79, 85, 80]
])

bonus = np.array([5, 10, 5, 10])
mnożnik = np.array([1.0, 1.1, 0.95, 1.15, 1.0])

print(f"Wyniki przed: {exams}")

Wyniki przed: [[78 85 92 88]
 [65 72 68 70]
 [90 88 95 92]
 [55 60 58 62]
 [82 79 85 80]]


In [6]:
wyniki_po = (exams + bonus) * mnożnik[:, np.newaxis]
#np.newaxis tworzy (5,1) (wcześniej było (5,)
#mnożnik[:] - wszystkie elementy
print(f"Wyniki po: {wyniki_po}")

Wyniki po: [[83.   95.   97.   98.  ]
 [77.   90.2  80.3  88.  ]
 [90.25 93.1  95.   96.9 ]
 [69.   80.5  72.45 82.8 ]
 [87.   89.   90.   90.  ]]
