Masz 2 punkty w przestrzeni 5-wymiarowej: <br>
- point_a = np.array([1, 2, 3, 4, 5])
- point_b = np.array([5, 4, 3, 2, 1])

Oblicz odległość Euklidesową: sqrt(sum((a - b)^2)) Następnie oblicz macierz odległości dla 4 punktów: <br>
points = np.random.rand(4, 5)

Wymagania:
Ręczna implementacja (bez gotowych funkcji)
Wynik: macierz 4x4 odległości między każdą parą punktów

In [1]:
import numpy as np

point_a = np.array([1, 2, 3, 4, 5])
point_b = np.array([5, 4, 3, 2, 1])


In [6]:
suma_kwadratow = sum((point_a - point_b) ** 2)
odleglosc_euklidesowa = np.sqrt(suma_kwadratow)
print(f"Odległość euklidesowa: {odleglosc_euklidesowa:.4f}")


Odległość euklidesowa: 6.3246


In [9]:
points = np.random.rand(4, 5)
macierz_odleglosci = np.zeros((4, 4))

for i in range(4):
    for j in range(4):
        roznica = points[i] - points[j]
        macierz_odleglosci[i, j] = np.sqrt(np.sum(roznica**2))

print(macierz_odleglosci)


[[0.         0.553573   0.84277346 1.10738596]
 [0.553573   0.         1.12844029 1.19007622]
 [0.84277346 1.12844029 0.         1.10510416]
 [1.10738596 1.19007622 1.10510416 0.        ]]
